[windows]
winvm ansible_host=192.168.1.25

[windows:vars]
ansible_user=Administrator
ansible_password=Password@123

ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
