[windows]
vm ansible_host=${{ secrets.WIN_HOST }}

[windows:vars]
ansible_user=${{ secrets.WIN_USER }}
ansible_password=${{ secrets.WIN_PASSWORD }}
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
